ipdk-io/ipdk

- build/IPDK_Container/scripts/build_p4c.sh
This review checkout's a specific SHA for P4C code base.
P4C executable is built and validated with this review.
Change-type: ImplementationChange
Title: Checkout specific SHA for P4C repository
Signed-off-by: n-sandeep <sandeep.nagapattinam@intel.com>
> Checkout specific SHA for P4C repository

- build/IPDK_Container/scripts/build_p4sde.sh
This review fixes issue 13:
a) Right now target-utils and target-syslibs repositories are being cloned
as a new repository and built separately. However, these repositories
are also being cloned as a submodule to p4-driver.
b) Build to these repositories also will happen from the submodules and
this library will be used by P4-OvS.
Change-type: DefectResolution
Title: IPDK: Update SDE script to use dependent code from submodules
Signed-off-by: n-sandeep <sandeep.nagapattinam@intel.com>
> IPDK: Update SDE script to use dependent code from p4-driver submodules

- build/IPDK_Container/Makefile
- build/IPDK_Container/Ubuntu20.04/Makefile
- build/IPDK_Container/examples/vhost-to-vhost/build_ubuntu_vm_image.sh
- build/IPDK_Container/examples/vhost-to-vhost/start_vm.sh
- build/IPDK_Container/scripts/build_p4c.sh
- build/IPDK_Container/scripts/build_p4sde.sh
- build/IPDK_Container/scripts/get_p4ovs_repo.sh
- build/IPDK_Container/scripts/os_ver_details.sh
- build/IPDK_Container/scripts/run_ovs.sh
- build/IPDK_Container/scripts/set_hugepages.sh
- build/IPDK_Container/start_p4ovs.sh
This commit adds a "shellcheck" Makefile target, and fixes all of
the bash scripts to pass a shellcheck [1] run. Shellcheck does
static analysis of bash scripts. In the past, it's saved me hours
of debugging things in production, I find it useful to use early
in a projects lifetime. Once we have proper CI/CD for IPDK, we'd
want to run the "shellcheck" target on each pull request before
merging, for example.
[1] https://github.com/koalaman/shellcheck
> shellcheck: Make all bash scripts pass shellcheck

- build/IPDK_Container/Dockerfile
- build/IPDK_Container/README
- build/IPDK_Container/Ubuntu20.04/Dockerfile
This makes the build of the Docker image for IPDK complete building all
P4 related components, meaning you can now then run the container using
`make volume` multiple times without have to go through the 20+ minute
build of the components each time.
Related to Issue #24
> Dockerfile: Build all P4 components

- build/IPDK_Container/scripts/os_ver_details.sh
This adjusts get_num_cores() to handle the case where NUM_CORES and
NUM_THREADS are already set by the caller.
Closes #26
> get_num_cores: Handle values being set

- build/IPDK_Container/Dockerfile
- build/IPDK_Container/scripts/build_p4c.sh
- build/IPDK_Container/scripts/set_hugepages.sh
Docker image is taking ~13GB as of today.
Below changes are made in this review which would reduce ~6.5GB.
a) Install only necessary packages when building a docker image.
b) Run start_p4ovs.sh script as part of docker build.
c) Remove source code of dependent packages which are installed as
part of install_dep_packages.sh
d) Make clean once P4-OVS and P4C are build and installed. For now,
source code is left intentionally as it would help in further
code reference and developments for user.
(subsequent commits will have this for p4-driver as well)
e) Changes are made in set_hugepages.sh, when we have more than one node
and once hugepages value is set for both nodes, this value is being
re-set once /sys/kernel/mm/hugepages/hugepages-2048kB is set to 1024.
This will not have an effect when …
> IPDK: Optimize docker image

- build/IPDK_Container/README
- build/IPDK_Container/scripts/run_cleanup.sh
- build/IPDK_Container/scripts/set_hugepages.sh
- Review is raised to enable "make clean" option in p4-driver
repository to reduce memory when KEEP_SOURCE_CODE flag is YES
- Update README with some more context
Change-type: Other
Title: IPDK: Enable make clean for p4-driver repository
Signed-off-by: n-sandeep <sandeep.nagapattinam@intel.com>
> IPDK: Enable make clean for p4-driver repository

- build/IPDK_Container/README_HOST_INSTALL.md
- build/IPDK_Container/scripts/get-image.sh
- build/IPDK_Container/scripts/host_install.sh
- build/IPDK_Container/scripts/run_cleanup.sh
- build/IPDK_Container/scripts/rundemo.sh
- build/IPDK_Container/scripts/set_hugepages.sh
- build/IPDK_Container/start_p4ovs.sh
- build/IPDK_Container/vagrant/.gitignore
- build/IPDK_Container/vagrant/Vagrantfile
- build/IPDK_Container/vagrant/provision.sh
Add a Vagrant environment, which makes testing a bit easier. Instructions are added on how to use the environment.
Note, I had to modify a few scripts to allow for integration with the Vagrant environment.
Closes Issue #36
> vagrant: Add Vagrant environment

- build/IPDK_Container/start_p4ovs.sh
119c5a6c introduced a shellcheck regression.
> shellcheck: Fix shellcheck error

- build/IPDK_Container/scripts/host_install.sh
This fixes the copying of directores so they are copied into the
appropriate place.
> host_install.sh: Fix copy of directories

- build/IPDK_Container/scripts/build_p4c.sh
This enables the building of the eBPF backend when building p4c.
> build_p4c.sh: Enable eBPF p4c backend

- build/IPDK_Container/README_DOCKER.md
- build/IPDK_Container/ipdk
This commits adjusts README_DOCKER.md to correct some blank line issues,
and updates a few other sections while I'm in here. I also removed the
ipdk link at the directory level and adjusted the documentation to
directly reference ipdk.sh instead, which feels cleaner to me.
After this merges, I'd like to next remove the old container build
system, and find a better home for the Vagrant setup as well.
> docs: Update README_DOCKER.md file

- build/IPDK_Container/README_HOST_INSTALL.md
- build/IPDK_Container/scripts/host_install.sh
This fixes the errors identified in #58 where the top-level sourcing of
the file `os_ver_details.sh` wasn't being done with a full path. I also
updated the instructions in README_HOST_INSTALL.sh to address the
example in there.
Closes #58
> host_install.sh: Source os_ver_details.sh

- build/README_DOCKER.md
The documentation incorrectly stated to use `--proxy` to build with a
proxy, but the code expects `--use-proxy`. Update the documentation to
match the code.
> container build: Fix proxy documentation

- build/README_NATIVE.md
When #60 was merged, I forgot to update the proxy usage of
host_install.sh to match the non-proxy use case. This corrects that
mistake.
Closes #65
> docs: Correct proxy usage of host_install.sh

- build/Dockerfile.ubuntu
The [`protobuf-compiler-grpc`](https://packages.debian.org/sid/amd64/protobuf-compiler-grpc/filelist) package provides the `grpc_cpp_plugin` binary dependency.
```bash
protoc -I./external/googleapis -I/usr/local/include -I./p4runtime/proto --grpc_out=./p4proto/p4rt/proto --plugin=protoc-gen-grpc=`which grpc_cpp_plugin` ./p4runtime/proto/p4/v1/p4runtime.proto
: program not found or is not executable
--grpc_out: protoc-gen-grpc: Plugin failed with status code 1.
```
This problem has been reported in: https://github.com/ipdk-io/ipdk/issues/76
> build: install protobuf grpc plugin

- build/Dockerfile.ubuntu
- build/start_p4ovs.sh
On older bash versions == operator doesn't work with [..] operator.
Due to this, depending on bash versions on your system,
install_dep_packages.sh script which install gflags and other
important dependencies will not run and you will run into packages
missing issue. This patch also minimum requirement for ninja version
based on meson requirement otherwise build will fail with error "
Could not detect Ninja v1.8.2 or newer"
Title: Fix issue 82
Change-type: DefectResolution
> ipdk: Fix issue 82

- build/scripts/os_ver_details.sh
Fixes os_ver_details.sh to always add -j in front of the number of
threads since this is passed directly to make.
Closes #85
> os_ver_details.sh: Always add -j to NUM_THREADS

- build/Dockerfile.fedora
- build/Dockerfile.ubuntu
- build/patches/PATCH-01-P4C
- build/scripts/build_p4c.sh
- build/start_p4ovs.sh
This patch introduce required changes to make P4C compatible with
protobuf 3.18.x. Updated dependencies are compatible with Ubuntu as well
as Fedora versions
Title: Changes required to make P4C compatible with updated protobuf
Change-type: Other
> ipdk: Changes required to make P4C compatible with updated protobuf

- .github/workflows/makefile.yml
This enables GitHub Actions to do basic CI on pull requests to the IPDK
repository. For now, it's actually a bit of a brute force approach, in
that we dynamically configure each Runner with the tools we need,
including Docker. We next run shellcheck, followed by the full build.
Some ways to optimize this in the future:
* Build our runner which has all the tools configured and installed.
* Modularize the build a bit to remove redundant steps.
* Work to get patches into upstream projects so we don't have to build
them each time.
Closes #88
> actions: Enable GitHub actions

- build/README_DOCKER.md
- build/scripts/ipdk-lib.sh
- build/scripts/ipdk.sh
- build/scripts/ipdk_default.env
This option adds the option to configure IPDK CLI to a predefined IPDK runtime environment as described in #72. The current predefined IPDK runtime environments are:
- default: configure the default environment (currently Fedora33 container)
- host: configure for a Vagrant/other VM or bare metal environment
- fedora33: fedora core 33 container environment
- ubuntu2004: ubuntu 20.04 container environment
- ubuntu1804: ubuntu 18.04 container environment
The `host` environment option is a preparation for another development to integrate the Vagrant and Bare metal flow in the CLI.
> Implement ipdk install [environment] option

- README.md
- build/README.md
This makes the IPDK build instructions much clearer by putting a note in
the top-level README.md file on how to perform a build.
> README: Make build instructions explicit

- build/scripts/host_install.sh
- build/start_p4ovs.sh
This makes sure to call all bash scripts with the bash shell, rather
than simply sh.
Also, d899a88 added the patches directory, but noone updated the
host_install.sh script. This fixes the build on native hosts.
> bash: Call bash scripts using bash

- build/Makefile
- build/scripts/run-shellcheck.sh
This adds a simple script to wrap around shellcheck which finds all bash
scripts and runs shellcheck on them. It is inspired by [1].
Prior to this, the CI was not actually running shellcheck on any scripts
in the scripts directory.
[1] https://github.com/koalaman/shellcheck/issues/143#issuecomment-909009632
> shellcheck: Fix shellcheck to actually run

- CONTRIBUTING.md
- MAINTAINERS.md
This adds a document describing how to contribute to IPDK. It also adds
an explicit list of maintainers.
> contributing: Add contributors document

- .github/workflows/makefile.yml
- build/scripts/ipdk-lib.sh
- build/scripts/ipdk.sh
- build/scripts/ipdk_default.env
Implements large parts of #101
Expanded IPDK CLI commands and options with:
- Support `ipdk config [key]=[value]` for setting key=value in ~/.ipdk/ipdk.env
- Support `ipdk build --platform [docker buildx supported platforms]` for local and multiarch builds
- Support `ipdk build --tags [taglist] --labels [labellist] --push --export [filename]`
- Support `ipdk start --platform [docker buildx supported platform]`
- Support `ipdk tag [tag]` for local image builds
- Support `ipdk export [filename]` for local image builds
- Support `ipdk push [tag]` for local image builds
- check for support of `docker buildx` on host system
Example:
`ipdk build --no-cache --platform linux/arm64` builds a ARM64 based ipdk image if run on a linux/amd-64 based host system
`ipdk start --platform linux/arm64` …
> Improve IPDK cli and ci build/run with buildx, multiarch, artefacts and push to registries

- build/scripts/set_hugepages.sh
According to available hugepages configuration under /proc/mounts,
configure the required amount of pages so as to have 2GB total.
Signed-off-by: Asaf Ravid <aravid@marvell.com>
> ipdk: support various-sized hugepages

- .github/workflows/makefile.yml
This fixes the build by quoting all tags passed to docker.
> Fix the build

- build/scripts/ipdk-lib.sh
Just follow the echo comment and use the DOCKER_CLI_EXPERIMENTAL environment variable instead of trying to change the docker config file with external commands that could not be available on host systems.
Solves reported issues...
Signed-off-by: stolsma <github@tolsma.net>
> Fix docker experimental check

- build/networking/README_NATIVE.md
- build/networking/scripts/host_install.sh
- build/networking/vagrant-container/Vagrantfile
- build/networking/vagrant-native/Vagrantfile
Commit 3ecf06e moved things around such that there is now a
`build/networking` directory. Some things were not adjusted to reflect
this new directory structure. This commit fixes these areas.
> location: Fixes from directory structure PR

- build/networking/scripts/ipdk-lib.sh
Currently check_buildx in builds/networking/scripts/ipdk-lib.sh only
checks update-binfmt which is Ubuntu binfmt_misc facilities. Fedora uses
service systemd-binfmt. So add checking of this if distribution is Fedora.
Signed-off-by: Jason Zeng <jason.zeng@intel.com>
> Enable docker image cross build on Fedora

- build/scripts/ipdk.sh
Per Sander, use the variable container name.
> ipdk.sh: Use $CONTAINER_NAME instead of ipdk

- build/networking_ebpf/scripts/host_install.sh
Now that [1] merged, psabpf-ctl is a shared library in addition to a CLI
tool. However, this means we should correctly setup LD_LIBRARY_PATH in
the p4-ebpf IPDK container. Without this, you cannot run psabpf-ctl, as
seen on these failing CI jobs in the opi-poc GitHub repo [2].
[1] https://github.com/P4-Research/psabpf/pull/31
[2] https://github.com/opiproject/opi-poc/actions/runs/2271748281
> p4-ebpf: Setup LD_LIBRARY_PATH correctly

- build/networking_ebpf/README.md
- build/networking_ebpf/scripts/host_install.sh
Commit [1] added proper shared library generation for psabpf. This
commit ensures IPDK p4-eBPF builds with the shared library support
enabled.
[1] https://github.com/P4-Research/psabpf/pull/34
> eBPF: Build psabpf as shared library

- build/storage/scripts/vm/prepare_vm.sh
- build/storage/scripts/vm/run_vm.sh
- build/storage/tests/it/test-drivers/init.hot-plug
- build/storage/tests/it/test-drivers/test-helpers
- build/storage/tests/it/traffic-generator/Dockerfile
- build/storage/tests/it/traffic-generator/init
There were 2 different ways to run the virtual machine for the integration tests and recipes. This patch gets rid of one of them and uses `scripts/vm/run_vm.sh` to run the vm for the integration tests.
> Reuse run_vm script in storage integration tests

- build/storage/tests/ut/host-target/test_run_grpc_server.py
- build/storage/tests/ut/run.sh
- build/storage/tests/ut/run_all_unit_tests.sh
jenkins does not provide TTY input device. Based on that, we should avoid allocation of pseudo-tty devices for our unit-test container.
Also in this patch some puzzling grpc error logs are suppressed
> Improve storage unit tests to run on CI

- build/storage/scripts/vm/prepare_vm.sh
Originally Fedora 33 was used to run the storage vm. This qemu image was moved to archive and we are moving to Fedora 36
> Update storage vm to fedora 36

- build/storage/recipes/environment_setup.md
The New base image(fedora:36) uses glibc >= 2.34 which relies on
clone3(2) sys call. Docker <= 20.10.9 is not able to serve that
sys call properly.
Setup the required docker version to 21.10.10 in the storage
recipes to avoid this error.
> Update docker installation guideline for storage.

- build/storage/recipes/environment_setup.md
- build/storage/scripts/run_container.sh
- build/storage/scripts/run_host_target_container.sh
- build/storage/scripts/run_proxy_container.sh
- build/storage/scripts/run_storage_target_container.sh
- build/storage/scripts/vm/prepare_vm.sh
This patch allows to run any of 3 storage containers in detached mode, if `AS_DAEMON` env variable is set to `true`
Also, this patch is a good opportunity to start refactoring the code which is responsible for running the containers in recipes.
Here some duplication is moved into a common `run_container.sh` file.
> Add ability to run storage containers as daemons

- MAINTAINERS.md
> Add Boris Glimcher as a Maintainer

- build/storage/scripts/disk_infrastructure.sh
- build/storage/tests/it/test-drivers/init.fio
- build/storage/tests/it/test-drivers/init.hot-plug
- build/storage/tests/it/test-drivers/init.scale-out
Ramdrive size is specified in MBs for `create_ramdrive_and_attach_as_ns_to_subsystem` calls.
> Ramdrive size is specified in MBs at creation.

- build/storage/.gitignore
- build/storage/Dockerfile
- build/storage/core/host-target/customizations/README.md
- build/storage/core/host-target/device_exerciser_customization.py
- build/storage/core/host-target/device_exerciser_kvm.py
- build/storage/core/host-target/host_target_grpc_server.py
- build/storage/core/host-target/host_target_main.py
- build/storage/core/host-target/init
- build/storage/core/host-target/pci_devices.py
- build/storage/scripts/run_host_target_container.sh
- build/storage/tests/it/test-drivers/init.fio
- build/storage/tests/it/test-drivers/init.scale-out
- build/storage/tests/ut/host-target/test_device_exerciser_customization.py
- build/storage/tests/ut/host-target/test_device_exerciser_kvm.py
- build/storage/tests/ut/host-target/test_it_create_customized_device_exerciser.py
- build/storage/tests/ut/host-target/test_pci_devices.py
- build/storage/tests/ut/host-target/test_run_grpc_server.py
IPDK is planned as target-agnostic set of drivers/tools etc.
Based on that we need to provide an ability to run our services with different target platforms. host-target container is one of them and it should be able to detect a disk to run traffic against by means of SPDK SMA opaque handle. For that purpose, ability to run custom device exerciser is added.
> Add host-target customization capability.

- build/storage/Dockerfile
- build/storage/core/host-target/device_exerciser_customization.py
- build/storage/core/host-target/device_exerciser_if.py
- build/storage/core/host-target/device_exerciser_kvm.py
- build/storage/core/host-target/fio_args.py
- build/storage/core/host-target/fio_runner.py
- build/storage/core/host-target/host_target_grpc_server.py
- build/storage/tests/it/test-drivers/init.fio
- build/storage/tests/ut/host-target/test_device_exerciser_customization.py
- build/storage/tests/ut/host-target/test_device_exerciser_kvm.py
- build/storage/tests/ut/host-target/test_fio_args.py
- build/storage/tests/ut/host-target/test_fio_runner.py
- build/storage/tests/ut/host-target/test_host_target_grpc_server.py
- build/storage/tests/ut/host-target/test_it_create_customized_device_exerciser.py
Currently fio arguments are provided as command line strings.
This can be inconvenient for parsing/modification and this patch accepts incoming fio args to host-traget service in json format.
> Use json format for fio args in host-target

- build/networking/scripts/build_p4sde.sh
- build/scripts/ipdk-lib.sh
- build/scripts/run-shellcheck.sh
- build/storage/scripts/build_container.sh
- build/storage/scripts/run_host_target_container.sh
- build/storage/scripts/run_ipu_storage_container.sh
- build/storage/scripts/run_storage_target_container.sh
- build/storage/scripts/sma_config_file.sh
- build/storage/scripts/vm/run_vm.sh
- build/storage/tests/it/run.sh
- build/storage/tests/it/test-drivers/init.fio
- build/storage/tests/it/test-drivers/init.hot-plug
- build/storage/tests/it/test-drivers/init.scale-out
- build/storage/tests/it/test-drivers/test-helpers
This allows shellcheck to fail correctly on errors, something it was not
doing previously.
Fixed in opi-poc here [1].
[1] https://github.com/opiproject/opi-poc/pull/114
> shellcheck: Fix shellcheck

- .github/dependabot.yml
This moves to ensuring each directory containing a Dockerfile has a path
element in the dependabot configuration.
> dependabot: Update dependabot docker config

- .github/workflows/linters.md
This adds the hadolint [1] Dockerfile linter to the IPDK CI.
[1] https://github.com/hadolint/hadolint
> linters: Add hadolint Dockerfile linter

- build/storage/scripts/disk_infrastructure.sh
On some platforms lsblk is not able to provide information regarding virtio-blk underlying chain of subsystems. Instead, in this patch 'vd' prefix is used to identify disk as virtio-blk.
> Use 'vd' prefix to identify virtio-blk disks.

- build/networking/Dockerfile.fedora
- build/networking/Dockerfile.ubuntu
This patch introduces installing numactl package to
avoid issues with memory initialization when OVS is started.
Per "https://developers.google.com/protocol-buffers/docs/news/2022-05-06",
protobuf version is updated to 3.20.1 to avoid issues with
ovs-p4ctl utility
Title: Install numactl package and specific protobuf version
> Install numactl package and specific protobuf version

- RELEASENOTES.md
- build/networking/Dockerfile.fedora
- build/networking/Dockerfile.ubuntu
- build/networking/patches/ipdk_p4c_001.patch
- build/networking/scripts/build_p4c.sh
- build/networking/scripts/build_p4sde.sh
- build/networking/scripts/get_p4ovs_repo.sh
- build/networking/scripts/host_install.sh
Build script changes to update the P4 OvS, P4 SDE and
P4C modules to ipdk release 22.07 tags or SHA.
Also additional changes to apply P4C patch on top of
open source latest SHA.
> ipdk: Update p4 modules to latest SHA

- build/storage/Dockerfile
- build/storage/core/host-target/requirements.txt
All host-target dependencies should be collected into requirements.txt file since some analyzers use requirements.txt file to perform checks.
> Use requirements.txt to install host-target deps.

- BUILDING.md
- build/README.md
I spent a lot of time looking for build instructions ...
and couldn't find them, so I'm proposing we keep
the symlink in the top-level to prevent any confusion.
IMHO "Where is the documentation" is not a good place for
subtlety/innovation :-)
> Linking main building instructions to the root dir

- build/storage/Dockerfile
- build/storage/recipes/environment_setup.md
- build/storage/scripts/build_container.sh
- build/storage/scripts/run_cmd_sender.sh
Sending cmds from test-driver confuses users.
To avoid this commands to storage containers will be sent from dedicated container.
> Run storage cmd-sender as separate container.

- build/storage/scripts/vm/prepare_vm.sh
- build/storage/scripts/vm/run_vm.sh
- build/storage/tests/it/test-drivers/test-helpers
In this patch, it is checked if all required tools to run host-target are copied into vm.
In case, host-target didn't start, additional information will be printed in tests.
> Improve host-target validity check.

- build/networking/scripts/start.sh
Modified utility script.sh to use the custom P4 OvS path for setting PATH and LD_LIBRARY_PATH environment variables
> Fix PATH variable configurations in start.sh utility script

- build/scripts/ipdk-lib.sh
Modified create_images method to address the
improper quoting pattern used in removing the
old images
> Fix improper quoting in ipdk-lib.sh

- build/storage/core/host-target/helpers/fio_args.py
- build/storage/recipes/nvme/fio.md
- build/storage/recipes/virtio-blk/fio.md
- build/storage/tests/ut/host-target/test_fio_args.py
In the previous version, if a fio is run to exercise all volumes attached to a device, all of them are exercised within a single job. However, it produced a joint report which does not show results for each volume separately. It can be inconvenient for the end user, if a per-volume statistic is needed.
In this patch, all volumes are exercised within their own fio job, and a separate report is shown for each device.
> Run fio against multiple volumes with dedicated jobs.

- build/storage/core/host-target/fio_runner.py
- build/storage/core/host-target/sma_handle.py
- build/storage/tests/it/ptf_tests/system_tools/config.py
- build/storage/tests/it/ptf_tests/system_tools/test_platform.py
- build/storage/tests/it/ptf_tests/tests/test_deploy_containers.py
- build/storage/tests/ut/host-target/test_fake_sys_fs.py
- build/storage/tests/ut/host-target/test_pci_devices.py
Bandit warns about subprocess usage, which is vulnerable to shell injections. However, this module is needed to run fio against devices. The required parameters were added to avoid shell injections and bandit warnings were suppressed.
> Fix bandit warnings in storage code.

- build/storage/core/ipu-storage-container/init
- build/storage/scripts/run_ipu_storage_container.sh
- build/storage/scripts/run_storage_target_container.sh
Storage-target and ipu-storage-container use SPDK inside. It can be useful to pass spdk arguments from upper level, for example to set core for reactor.
In this patch, SPDK arguments can be passed by means of SPDK_ARGS environment variable.
> Pass spdk arguments outside of containers.

- build/storage/scripts/disk_infrastructure.py
- build/storage/scripts/vm/prepare_vm.sh
Qemu with vfio-user actively produces logs and some of them were printed directly into console. Sometimes it could lead to incorrect device count, since devices printed into kernel logs were taken into account and delay was needed at device creation to mitigate that case.
After this patch, only emergency kernel logs will pop up into console.
> Disable kernel logs to print into console for storage vm.

- .github/workflows/makefile.yml
Since `::set-output` has been deprecated this PR substitutes it with the newest output mechanism of GitHub workflow, in this way, we won't see the related warning in the Action.
> GitHub Workflow: changed ::set-output with $GITHUB_OUTPUT

- build/storage/Dockerfile
- build/storage/core/host-target/requirements.txt
Default protobuf version contains denial of service vulnerability described in SNYK-PYTHON-PROTOBUF-3031740.
Use explicit protobuf version 3.20.2 to overcome that issue. Use explicit host-target python packages to cover them by CI SNYK scans.
> Use explicit versions of vulnerable python packages.

- build/storage/Dockerfile
- build/storage/recipes/environment_setup.md
- build/storage/scripts/vm/install_qemu.sh
- build/storage/scripts/vm/run_vm.sh
- build/storage/scripts/vm/vm_default_variables.sh
IPDK relies on SPDK to cover KVM capabilities. To avoid any issues, IPDK should rely on the same version of QEMU used by SPDK.
> Rely on SPDK for QEMU install.

- build/storage/scripts/build_container.sh
- build/storage/scripts/run_cmd_sender.sh
- build/storage/scripts/run_container.sh
- build/storage/scripts/run_host_target_container.sh
- build/storage/scripts/run_ipu_storage_container.sh
- build/storage/scripts/run_storage_target_container.sh
- build/storage/scripts/vm/prepare_vm.sh
All run_*_container.sh will try to fetch corresponding images from public IPDK registry first if git head is on main branch. This should improve user experience since no need to wait when images are built.
If building is preferable way to get images, then BUILD_IMAGE=true environment variable should be set.
If any customization for host-target is detected in default directory or specified in env var, local build we be run.
If it is needed to avoid fetching/building of images, DO_NOT_FETCH_OR_BUILD_IMAGE=true should be set.
> Fetch published images in storage scripts for manual scenarios

- build/storage/Dockerfile
- build/storage/core/host-target/requirements.txt
Setuptools is used as dependency of grpcio-tools package. Snyk scans discovered new vulnerability in it, thus new fixed version without vulerability is used.
> Use setuptools package without vulerability for storage.

- build/storage/recipes/environment_setup.md
- build/storage/recipes/nvme/crypto.md
Crypto recipe is extended with an important note to the end-user regarding the solution since crypto keys are passed in plain text between the containers.
Signed-off-by: Filip Szufnarowski <filip.szufnarowski@intel.com>
> Provide security-related notes to crypto recipe.

- build/networking/scripts/distro_pkg_install.sh
Modified distro packages installation script to include openssl package required for gRPC TLS client-server communication.
> Add openssl package required for gRPC TLS

- build/storage/Dockerfile
- build/storage/core/cmd-sender/requirements.txt
- build/storage/scripts/disk_infrastructure.py
Shell was used in storage to call grpc_cli tool. However, shell calls are treated as unsafe by some code scanners and they have to be replaced with some more reliable approaches.
> Eliminate shell calls in storage.

- RELEASENOTES.md
Updating the IPDK 23.07 release notes to include the gRPC 1.54.2 update which fixes three CVEs
> Update IPDK 23.07 release notes to include gRPC CVE fixes

- build/networking/scripts/build_p4c.sh
- build/networking/scripts/build_p4sde.sh
- build/networking/scripts/download_nr_src_code.sh
This commit is to update the networking container to IPDK 23.07 release
>  Updated SHA for p4c, p4sde and infrap4d for IPDK 23.07

- build/networking/scripts/build_p4c.sh
- build/networking/scripts/build_p4sde.sh
- build/networking/scripts/download_nr_src_code.sh
Updating the `main` branch with the 23.07 release image SHA values for building networking-recipe container
> Update p4c, psde and infrap4d SHA for 23.07 release

- build/networking/scripts/build_p4c.sh
- build/networking/scripts/distro_pkg_install.sh
Address two build issues:
> Missing 'netaddr' module. Updated install script to provide it.
> Compile errors in P4C. The latest P4C compiler uses some code from bmv2 , so it shouldn't be disabled. Removed 
ENABLE_BMV2=OFF from the cmake command. Verified with compiler team that this is correct.
> Update networking container to fix unused p4c flag & add new dependencies

- build/networking/README.md
- Replace links to individual documents with a link to the P4 Control Plane User Guide.
- Correct link to security guide.
> Update links in networking README

- RELEASENOTES.md
IPDK 24.01 release notes update for networking-recipe
> Adding networking-recipe release notes for IPDK 24.01
