- build/IPDK_Container/README
- build/IPDK_Container/Ubuntu20.04/Dockerfile
- build/IPDK_Container/Ubuntu20.04/Makefile
- build/IPDK_Container/Ubuntu20.04/docker.env
- build/IPDK_Container/examples/vhost-to-vhost/start_vm.sh
- build/IPDK_Container/scripts/build_p4sde.sh
- build/IPDK_Container/scripts/os_ver_details.sh
- build/IPDK_Container/start_p4ovs.sh
Signed-off-by: Mohammad Abdul Awal <mohammad.abdul.awal@intel.com>
> Created container with Ubuntu20.04

- build/IPDK_Container/README
- build/IPDK_Container/docker.env
This review fixes issue 10:
a) Commented proxy parameter in docker.env
b) Updated README regaridng proxy usage.
Change-type: DefectResolution
Title: IPDK: Comment proxy parameter and update README
Signed-off-by: n-sandeep <sandeep.nagapattinam@intel.com>
> IPDK: Comment proxy parameter and update README

- build/IPDK_Container/Ubuntu20.04/Dockerfile
This reduces the container image size from 13G to 6G.
Relates to #29
Relates to #11
> ubuntu: Update Dockerfile to trim resulting image

- build/IPDK_Container/Dockerfile
- build/IPDK_Container/Makefile
- build/IPDK_Container/README
- build/IPDK_Container/Ubuntu20.04/Dockerfile
- build/IPDK_Container/Ubuntu20.04/Makefile
- build/IPDK_Container/Ubuntu20.04/docker.env
- build/IPDK_Container/docker.env
- build/IPDK_Container/run_ovs_cmds
- build/IPDK_Container/scripts/run_cleanup.sh
As part of docker build, after successfully starting p4ovs via
start_p4ovs.sh option is given to user for reducing this memory by setting
'KEEP_SOURCE_CODE' variable in docker.env file.
a) If 'KEEP_SOURCE_CODE=NO' then:
i) Copy few dependent scripts from P4-OVS repository to scripts directory.
ii) Removing complete source code for P4-OVS repository.
iii) Removing complete source code of p4-driver repository.
iv) Removing complete source code of P4C.
v) Removing source code of dependent packages installed as part of
install_dep_packages.sh script.
b) If 'KEEP_SOURCE_CODE=YES' then:
i) Removing object files via make clean for P4-OVS repository.
ii) Removing object files via make clean for p4-driver repository (**TODO).
iii) Removing object files via make clean for P4C.
iv) Removing source …
> IPDK: Optimize docker image based on user option

- build/IPDK_Container/scripts/host_install.sh
> Use pushd instead of cd

- build/IPDK_Container/README_HOST_INSTALL.md
> Fix markdown formatting

- build/IPDK_Container/Dockerfile.fedora
- build/IPDK_Container/Dockerfile.ubuntu
- build/IPDK_Container/README_DOCKER.md
- build/IPDK_Container/ipdk
- build/IPDK_Container/scripts/ipdk-lib.sh
- build/IPDK_Container/scripts/ipdk.sh
- build/IPDK_Container/scripts/ipdk_default.env
- build/IPDK_Container/scripts/run_ovs.sh
- build/IPDK_Container/scripts/start.sh
@jfingerh wanted some more 'helpers' for using this repo with docker and It's always handy to have some helpers ;) so I extended the Makefile with some more docker helpers. This is still "Work In Progress" as I changed a lot in the Makefile and I'm not sure yet what to do with the two script files I added in the volume directory.
What changed? Next to the normal `make run` that just starts the container and stays in the container command line I added `make runp4ovs` that runs the created image as a docker daemon that automatically starts p4-ovs. With `make connect` can then be connected to the running container. Also `make log` can be used to show the output of the container to standard out.  
I Also implement a move to local directory use as running container /tmp volume as I proposed in …
> Scripts and docs for better (docker) user experience 

- build/IPDK_Container/scripts/ipdk.sh
> Adjust wording in help message

- build/Dockerfile.ubuntu
- build/scripts/build_p4c.sh
- build/scripts/build_p4sde.sh
- build/scripts/ipdk.sh
- build/scripts/ipdk_default.env
- build/scripts/run_ovs.sh
- build/scripts/rundemo.sh
- build/scripts/set_hugepages.sh
- build/scripts/start.sh
- build/start_p4ovs.sh
This patch adds Ubuntu18.04 support. Replaces source
with '.' to avoid erros when running shell scripts on
Ubuntu or old bash versions
Title: Add Ubuntu18.04 support
Change-type: Other
> ipdk: Add Ubuntu18.04 support

- .github/workflows/makefile.yml
> Fix CI issues

- README.md
- readme.md
Move readme.md to README.md, and add a CI link to the top.
> README: Update README

- build/README_DOCKER.md
Add some notes about the explicit nature of the Vagrant and Virtualbox
setup we support.
Related: #98
> Vagrant: Update instructions

- CONTRIBUTING.md
Commit 5359dc1 introduced a spelling error.
> CONTRIBUTING: Fix spelling error

- build/networking_ebpf/scripts/host_install.sh
- build/networking_ebpf/scripts/run_ebpf.sh
- build/networking_ebpf/vagrant/provision.sh
- build/scripts/ipdk.sh
> More cleanups for IPDK p4-eBPF

- build/networking_ebpf/README_DOCKER.md
> Fix broken link and remove WIP label from ipdk-plugin

- build/networking_ebpf/Makefile
- build/networking_ebpf/README_DOCKER.md
- build/scripts/ipdk.sh
> Fixes to make the IPDK p4-eBPF demo work

- MAINTAINERS.md
> Welcome to our new storage maintainers

- build/networking/scripts/build_p4sde.sh
Freezing SHA version of SDE for stability reasons
> Setting SDE SHA to stabilize builds

- build/inline_acceleration/firewall/README.md
- build/inline_acceleration/firewall/example/firewall.conf
- build/inline_acceleration/firewall/example/firewall.p4
- build/inline_acceleration/firewall/example/firewall_parser.p4
- build/inline_acceleration/firewall/example/protocols.p4
- build/inline_acceleration/firewall/example/vpp_firewall.conf
- build/inline_acceleration/firewall/example/vpp_startup.conf
- build/inline_acceleration/firewall/patch/0001-Implement-rte_flow-wrapper-call-from-the-ACL-plugin.patch
- build/inline_acceleration/firewall/patch/0003-net-virtio-added-rte_flow-capability.patch
- build/inline_acceleration/firewall/scripts/clean_rules.sh
- build/inline_acceleration/firewall/scripts/install_p4-ovs.sh
Signed-off-by: Mohammad Abdul Awal <mohammad.abdul.awal@intel.com>
> firewall inline acceleration recipe

- .github/workflows/first-interaction.yml
This adds the GitHub First Interaction [1] action into IPDK. It will display
a helpful message to new users who submit an issue or a pull request,
pointing them at the CONTRIBUTING.md, MAINTAINERS.md, and CI code.
[1] https://github.com/marketplace/actions/first-interaction
> actions: Add first interaction GitHub Action

- .github/workflows/first-interaction.yml
> Run on pull requests and first issue creation

- .github/workflows/markdown.yml
- README.md
> Add markdown lint status badge

- build/storage/recipes/README.md
- build/storage/recipes/environment_setup.md
- build/storage/recipes/fio.md
- build/storage/recipes/hot-plug.md
- build/storage/recipes/scale-out.md
This recipe describes how to hot-plug/hot-unplug 64 virtio-blk devices.
> Add storage scale-out recipe.

- build/networking/scripts/build_p4sde.sh
- build/networking/scripts/rundemo.sh
fix couple bugs in scripts @mestery
> couple bug fixes

- MAINTAINERS.md
> MAINTAINERS: Add Nupur Uttarwar

- README.md
> Move to Linters status badge

- .github/workflows/first-interaction.yml
> Add write permissions to first integration bot

- CHANGELOG.md
- RELEASENOTES.md
Extending of release notes and changelog files with storage-related content.
Signed-off-by: Filip Szufnarowski <filip.szufnarowski@intel.com>
> Storage content added to changelog and release notes

- build/storage/tests/it/test-drivers/test-helpers
Provide ability to set storage test ip addresses externally.
> Provide ability to set storage test ip addresses externally.

- build/storage/recipes/fio.md
Make the fio recipe match the implementation and provide fio arguments in JSON format
> Use json fio arguments in storage fio recipe.

- RELEASENOTES.md
Add release notes for Networking recipe for 22_07
Title: Add release notes for Networking recipe for 22_07
> ipdk: Add release notes for Networking recipe for 22_07

- RELEASENOTES.md
Also includes some explanation of the sections in release notes.
> Adds CI/CD section to RELEASENOTES.md plus formatting

- RELEASENOTES.md
> Linux distributions supported for container

- build/storage/scripts/disk_infrastructure.sh
- build/storage/tests/it/test-drivers/test-helpers
> Do not use proxy for grpc calls.

- build/scripts/ipdk-lib.sh
Signed-off-by: Okuniewska, Julia <julia.okuniewska@intel.com>
Fixes https://github.com/ipdk-io/ipdk/issues/232
> Fix bash command not found: change error to echo

- build/networking/README_NATIVE.md
- build/networking/scripts/host_install.sh
- build/networking/scripts/rundemo.sh
- build/scripts/ipdk_default.env
This adds the ability to specify a source location (`-d` option) to the
`host_install.sh` and `rundemo.sh` scripts.
Fixes #230
> native: Add ability to specify src location

- .github/workflows/storage-ci.yml
> Storage Unit Test Integration

- build/networking/Dockerfile.fedora
- build/networking/Dockerfile.ubuntu
- build/networking/scripts/set_hugepages.sh
`set_hugepages.sh` was not visible inside Docker build context
> Networking scenario build fails

- .github/workflows/storage-ci-skip.yml
Signed-off-by: Aravindkumar Mg <aravindkumar.mg@intel.com>
> added storage ut skip action

- build/storage/scripts/disk_infrastructure.py
This is a patch that solves issues with gRPC calls made with sma_client.
Signed-off-by: rilnickx <rafalx.ilnicki@intel.com>
> Suppress proxy environmental variables for SMA calls

- build/networking/scripts/build_p4c.sh
Modified P4C build script to disable all the components not required for network recipe.
> Optimize P4C DPDK Target install files

- build/storage/Dockerfile
- build/storage/core/host-target/device_exerciser_kvm.py
- build/storage/core/host-target/fio_args.py
- build/storage/core/host-target/pci_devices.py
- build/storage/core/host-target/volume.py
- build/storage/tests/ut/host-target/test_device_exerciser_kvm.py
- build/storage/tests/ut/host-target/test_fio_args.py
- build/storage/tests/ut/host-target/test_fio_runner.py
- build/storage/tests/ut/host-target/test_pci_devices.py
Host-target internal structure is updated to be extended with NVMe support.
> Update storage host-target internal structure.

- build/storage/tests/it/ptf_tests/python_system_tools/__init__.py
- build/storage/tests/it/ptf_tests/python_system_tools/ssh_terminal.py
An SSHTerminal class was implemented to provide a possibility to execute commands on the SSH server. This will be used in future test development. In addition folders and README.md files were added for future test development purposes.
> Add SSHTerminal

- build/storage/scripts/disk_infrastructure.py
- build/storage/scripts/disk_infrastructure.sh
> Add infrastructure methods for NVMe.

- build/storage/scripts/sma_config_file.sh
> Generate sma config on manual ipu-storage-container start.

- build/networking/scripts/rundemo.sh
- Update p4c executable path.
- Kill qemu VM's as part of cleanup.
- Observed issue with rundemo.sh when this script is triggered from path other than /root/. vm1.qcow2 and vm2.qcow2 are created in /root/ but if script is triggered from different path, starting VM fails as this image is not available.
- Observed intermittent issues when P4-OVS process has started but even before opening ports for gRPC clients, gnmi-cli is trying to create a port. Hence first port was never created.
eg: Added debug logs to check for '/tmp/vhost-user-0' and 'netsat -tunlp | grep ovs' to validte if P4-OVS hs opened gRPC ports. Logs: setting vhost_dev = true.Return grpc errno (14), Reason: failed to connect to all addresses Checking for /tmp/vhost-user-0 port ls: cannot access '/tmp/vhost-user-0': No such …
> Fix issues with rundemo.sh

- build/storage/scripts/vm/prepare_vm.sh
> Improve host-target service exit.

- build/storage/scripts/disk_infrastructure.py
- build/storage/scripts/disk_infrastructure.sh
add shell wrappers to set crypto on NVMe volumes
> Add shell wrappers to use NVMe crypto capabilities

- build/storage/tests/it/test-drivers/init.crypto.nvme
- build/storage/tests/it/test-drivers/init.fio.nvme
Signed-off-by: Filip Szufnarowski <filip.szufnarowski@intel.com>
> Fixing typos in test scripts.

- build/storage/Dockerfile
> Add healthcheck for storage containers.

- build/storage/core/spdk-app/init
> Improve storage-target exit if port is already used.

- build/storage/scripts/disk_infrastructure.py
> Improve error handling in storage shell wrappers.

- build/storage/scripts/run_container.sh
> Fix pre-built image fetching.

- build/storage/recipes/environment_setup.md
- build/storage/scripts/vm/prepare_vm.sh
> Add ability to change vm root password at build time.

- build/storage/tests/it/ptf_tests/system_tools/errors.py
- build/storage/tests/it/ptf_tests/system_tools/ssh_terminal.py
- build/storage/tests/it/ptf_tests/system_tools/test_platform.py
Signed-off-by: Kula <przemyslawx.kula@intel.com>
> [tests] Add Cmd Sender Exception and change paramiko policy

- build/storage/Dockerfile
- build/storage/scripts/run_cmd_sender.sh
- build/storage/scripts/run_container.sh
- build/storage/scripts/run_host_target_container.sh
> Set non-root user for cmd-sender.

- README.md
- build/README.md
Signed-off-by: Sandeep N <sandeep.nagapattinam@intel.com>
> Update README for referring correct Networking documents.

- build/storage/tests/it/ptf_tests/system_tools/ssh_terminal.py
Signed-off-by: Kula <przemyslawx.kula@intel.com>
> [tests] Change paramiko key policy

- build/networking/scripts/download_nr_src_code.sh
Signed-off-by: Sandeep N <sandeep.nagapattinam@intel.com>
> Update SHA from latest Networking-recipe code

- MAINTAINERS.md
> Kyle is no longer a maintainer

- build/storage/recipes/environment_setup.md
Signed-off-by: Filip Szufnarowski <filip.szufnarowski@intel.com>
> HW security measures note added.

- RELEASENOTES.md
Signed-off-by: Sabeel Ansari <sabeel.ansari@intel.com>
> Release notes for Networking Recipe 23.01

- build/networking/README_DOCKER.md
Signed-off-by: Sabeel Ansari <sabeel.ansari@intel.com>
> Update networking Docker readme

- RELEASENOTES.md
- build/networking/README_DOCKER.md
- build/networking/README_NATIVE.md
Signed-off-by: Sabeel Ansari <sabeel.ansari@intel.com>
> Update documentation based on comments + formatting fix

- RELEASENOTES.md
- build/networking/README_DOCKER.md
- build/networking/README_NATIVE.md
Signed-off-by: Sabeel Ansari <sabeel.ansari@intel.com>
> Documentation & formatting update for 23.01 branch

- RELEASENOTES.md
Signed-off-by: Dan Daly <dan.daly@intel.com>
> Release Notes CI update

- RELEASENOTES.md
Added release notes from main branch
> Final release notes merge from main

- build/storage/Dockerfile
> Fix cmd-sender script sourcing.

- build/storage/Dockerfile
> Update storage libs.

- build/storage/recipes/environment_setup.md
Adding two commands to recipes that makes build more stable
> adding kernel-headers and update

- RELEASENOTES.md
Updating release notes for ipdk_v23.07 from branch to main
> Update ipdk_v23.07 release notes on main branch
